### ISSUE TITLE
Images in header

### ISSUE THREAD

**Issue by LinusBrockmeyer** [tesla-software/chrome2pdf#1]
Hi @karlomikus,

i was not able to get an image working inside the header. Displaying it in the content inside fixed header tags worked, but then the footer was only displayed on the last page. I need the footer to display current pageNumber and total pageNumber so I could not move the footer into the content too.

Do you know a way to render an image inside the header? Or if it is possible to inject pageNumbers into the content?

Thank you in advance and best regards.

Linus

**Comment by karlomikus** [comment]
It looks like chrome [doesn't allow](https://nathanfriend.io/2019/04/15/pdf-gotchas-with-headless-chrome.html#headers-and-footers-cant-use-external-resources) external resources in header/footer region.
Also I don't think there is a way to insert header/footer variables like `pageNumber` into content.

**Comment by LinusBrockmeyer** [comment]
The link you provided was perfect. I coded the image as a base64 encoded string into the header template. This got rendered correctly by chrome. Thank you.
